"""add file_path and chunk_index to knowledge_chunks

Revision ID: 8d72e996b1e9
Revises: 98c4ea1a4f20
Create Date: 2026-09-03 20:14:31.104205

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d72e996b1e9'
down_revision: Union[str, Sequence[str], None] = '98c4ea1a4f20'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('answer_cache_query_embedding_idx'), table_name='answer_cache', postgresql_ops={'query_embedding': 'vector_cosine_ops'}, postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    op.add_column('knowledge_chunks', sa.Column('file_path', sa.Text(), nullable=True))
    op.add_column('knowledge_chunks', sa.Column('chunk_index', sa.Integer(), nullable=True))
    op.drop_index(op.f('knowledge_chunks_embedding_idx'), table_name='knowledge_chunks', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    op.create_unique_constraint('uq_chunk_source', 'knowledge_chunks', ['file_path', 'chunk_index'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_chunk_source', 'knowledge_chunks', type_='unique')
    op.create_index(op.f('knowledge_chunks_embedding_idx'), 'knowledge_chunks', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    op.drop_column('knowledge_chunks', 'chunk_index')
    op.drop_column('knowledge_chunks', 'file_path')
    op.create_index(op.f('answer_cache_query_embedding_idx'), 'answer_cache', ['query_embedding'], unique=False, postgresql_ops={'query_embedding': 'vector_cosine_ops'}, postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    # ### end Alembic commands ###
