"""enable pgvector extension and create initial schema

Revision ID: <auto-generated>
Revises:
Create Date: <auto-generated>
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import UUID, ARRAY
from pgvector.sqlalchemy import Vector

# revision identifiers, used by Alembic.
revision = "98c4ea1a4f20"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # 1. Enable pgvector — must happen before any Vector() column is created
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    # 2. Certifications
    op.create_table(
        "certifications",
        sa.Column("id", UUID(as_uuid=True), primary_key=True, server_default=sa.text("gen_random_uuid()")),
        sa.Column("title", sa.Text, nullable=False),
        sa.Column("issuer", sa.Text, nullable=False),
        sa.Column("date", sa.Text),
        sa.Column("field", sa.Text),
        sa.Column("file_url", sa.Text),
        sa.Column("description", sa.Text),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), server_default=sa.func.now()),
    )

    # 3. Projects
    op.create_table(
        "projects",
        sa.Column("id", UUID(as_uuid=True), primary_key=True, server_default=sa.text("gen_random_uuid()")),
        sa.Column("name", sa.Text, nullable=False),
        sa.Column("github_repo", sa.Text),
        sa.Column("tech_stack", ARRAY(sa.Text)),
        sa.Column("start_date", sa.Date),
        sa.Column("end_date", sa.Date),
        sa.Column("summary", sa.Text),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), server_default=sa.func.now()),
    )

    # 4. Knowledge chunks
    op.create_table(
        "knowledge_chunks",
        sa.Column("id", UUID(as_uuid=True), primary_key=True, server_default=sa.text("gen_random_uuid()")),
        sa.Column("source_type", sa.Text, nullable=False),
        sa.Column("project_id", UUID(as_uuid=True), sa.ForeignKey("projects.id", ondelete="CASCADE")),
        sa.Column("content", sa.Text, nullable=False),
        sa.Column("embedding", Vector(1024)),
        sa.Column("language", sa.Text, server_default="auto"),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), server_default=sa.func.now()),
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), server_default=sa.func.now()),
        sa.CheckConstraint(
            "source_type in ('personal_bio','experience','project_narrative','github_readme','certification')",
            name="knowledge_chunks_source_type_check",
        ),
    )
    op.execute(
        "CREATE INDEX ON knowledge_chunks USING ivfflat (embedding vector_cosine_ops) WITH (lists = 100)"
    )

    # 5. Sessions & messages
    op.create_table(
        "sessions",
        sa.Column("id", UUID(as_uuid=True), primary_key=True, server_default=sa.text("gen_random_uuid()")),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), server_default=sa.func.now()),
        sa.Column("last_active", sa.TIMESTAMP(timezone=True), server_default=sa.func.now()),
    )
    op.create_table(
        "messages",
        sa.Column("id", UUID(as_uuid=True), primary_key=True, server_default=sa.text("gen_random_uuid()")),
        sa.Column("session_id", UUID(as_uuid=True), sa.ForeignKey("sessions.id", ondelete="CASCADE")),
        sa.Column("role", sa.Text, nullable=False),
        sa.Column("content", sa.Text, nullable=False),
        sa.Column("tone_tag", sa.Text),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), server_default=sa.func.now()),
        sa.CheckConstraint("role in ('user','assistant')", name="messages_role_check"),
    )

    # 6. Answer cache
    op.create_table(
        "answer_cache",
        sa.Column("id", UUID(as_uuid=True), primary_key=True, server_default=sa.text("gen_random_uuid()")),
        sa.Column("query_hash", sa.Text, nullable=False),
        sa.Column("query_embedding", Vector(1024)),
        sa.Column("answer", sa.Text, nullable=False),
        sa.Column("sources", ARRAY(sa.Text)),
        sa.Column("project_id_tags", ARRAY(sa.Text)),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), server_default=sa.func.now()),
        sa.Column("expires_at", sa.TIMESTAMP(timezone=True)),
    )
    op.execute(
        "CREATE INDEX ON answer_cache USING ivfflat (query_embedding vector_cosine_ops) WITH (lists = 100)"
    )


def downgrade():
    op.drop_table("answer_cache")
    op.drop_table("messages")
    op.drop_table("sessions")
    op.drop_table("knowledge_chunks")
    op.drop_table("projects")
    op.drop_table("certifications")
    op.execute("DROP EXTENSION IF EXISTS vector")